version: '3.8'
services:
  dna-carro-api:
    image: node:16.14.2
    container_name: dna-carro-api
    command: sh -c "npm install && npm run start:debug"
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
      - '9230:9229'
    depends_on:
      - dna-carro-database
  dna-carro-database:
    image: postgres:15.3-alpine
    container_name: dna-carro-database
    volumes:
      - .:/app
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    command: -p ${DATABASE_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PORT=${DATABASE_PORT}
  dna-carro-cache:
    container_name: dna-carro-cache
    image: redis
    ports:
      - '${CACHE_PORT}:${CACHE_PORT}'
    volumes:
      - redis:/data
    env_file:
      - .env
volumes:
  redis:
    driver: local
