export const GOOGLE_GEOCODING_STATUS = {
  ZERO_RESULTS: 'ZERO_RESULTS',
};

export const GOOGLE_COUNTRY_CODE_ISO_3166_1 = {
  BRAZIL: 'BR',
};

export const GOOGLE_LANGUAGE_ACCEPT = {
  BRAZIL: 'pt-BR',
};
