export const COUNTRY_ADDRESS_CODE = {
  BRAZIL: 'BR',
};

const COMPONENT_TYPE_NUMBER = 'number';
export const COMPONENT_TYPE_STREET = 'street';
export const COMPONENT_TYPE_NEIGHBORHOOD = 'neighborhood';
export const COMPONENT_TYPE_CITY = 'city';
export const COMPONENT_TYPE_STATE = 'state';
const COMPONENT_TYPE_COUNTRY = 'country';
export const COMPONENT_TYPE_POSTAL_CODE = 'postalCode';

export const COMPONENT_ADDRESS_TYPES = [
  COMPONENT_TYPE_NUMBER,
  COMPONENT_TYPE_STREET,
  COMPONENT_TYPE_NEIGHBORHOOD,
  COMPONENT_TYPE_CITY,
  COMPONENT_TYPE_STATE,
  COMPONENT_TYPE_COUNTRY,
  COMPONENT_TYPE_POSTAL_CODE,
];
